version: '3.3'

services:
  db:
    image: mariadb:10.4
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: humhub
      MYSQL_USER:     humhub
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    volumes:
      - ./volumes/db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile.dev
    restart: always
    volumes:
      - ./humhub:/var/www/html
    ports:
      - 80:80
  composer:
    image: composer:1.8.5
    restart: "no"
    command: install --ignore-platform-reqs --no-scripts
    volumes:
      - ./humhub:/app
