FROM php:7.4-apache-buster

RUN ["/bin/bash", "-c", "set -xe"]
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "-y", "libonig-dev", "libfreetype6-dev", "libjpeg-dev", "libpng-dev", "libcurl4-openssl-dev", "libzip-dev", "libicu-dev", "libldap-dev", "imagemagick", "unzip", "pkg-config", "patch"]

RUN ["docker-php-ext-install", "-j2","curl", "mbstring", "pdo_mysql", "zip", "exif", "intl", "fileinfo", "ldap", "mysqli", "gd"]
RUN ["pecl", "config-set", "php_ini", "/usr/local/etc/php/php.ini"]
RUN ["pecl", "install", "APCu"]
RUN ["docker-php-ext-enable", "apcu.so"]

